# Generated by Django 4.2.6 on 2024-01-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0002_auto_20210722_1042"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="code",
            field=models.TextField(null=True, verbose_name="Code"),
        ),
    ]
