# Generated by Django 4.2.6 on 2024-01-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0003_category_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.TextField(blank=True, null=True, verbose_name="Code"),
        ),
    ]
