# Generated by Django 4.2.6 on 2024-01-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0004_alter_category_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
