# Generated by Django 4.2.6 on 2024-01-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0018_workoutsession_pr_post_session_left_hand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="decision_code",
            field=models.TextField(
                blank=True,
                help_text="Python code to decide whether this day should be proposed for the next workout. The code should return True or False.",
                null=True,
                verbose_name="Decision code",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="The priority of this day. Days with a higher priority are evaluated first when deciding which day to propose for the next workout.",
                verbose_name="Priority",
            ),
        ),
    ]
