# Generated by Django 4.2.6 on 2024-01-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0019_day_decision_code_day_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="is_dynamic",
            field=models.BooleanField(
                default=False,
                help_text="A dynamic workout chooses the day to be executed based on the formulas defined in the days",
                verbose_name="Dynamic workout",
            ),
        ),
    ]
